[terminal]
# Make this system dependant
shell = "ubuntu"
# shell = "pwsh.exe"
[env]
COLORTERM="truecolor"
TERM="xterm-256color"

[font]
size = 12
bold.family = ""
italic.family = ""
normal.family = "FiraCode Nerd Font"

[window]
padding = {x = 5, y = 5}

[keyboard]
bindings = [
    {key = "C", mods = "Control|Shift", action = "Copy"},
    {key = "V", mods = "Control|Shift", action = "Paste"},
]

## Everforest dark medium
# [colors.primary]
# background = "#2d353b"
# foreground = "#d3c6aa"
#
# [colors.normal]
# black = "#475258"
# red = "#e67e80"
# green = "#a7c080"
# yellow = "#dbbc7f"
# blue = "#7fbbb3"
# magenta = "#d699b6"
# cyan = "#83c092"
# white = "#d3c6aa"
#
# [colors.bright]
# black = "#475258"
# red = "#e67e80"
# green = "#a7c080"
# yellow = "#dbbc7f"
# blue = "#7fbbb3"
# magenta = "#d699b6"
# cyan = "#83c092"
# white = "#d3c6aa"

# Kanso Mist
[colors.primary]
background = '#22262D'
foreground = '#C5C9C7'

[colors.normal]
black = '#22262D'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#a4a7a4'

[colors.bright]
black = '#5C6066'
red = '#e46876'
green = '#87a987'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#C5C9C7'

[colors.selection]
background = '#43464E'
foreground = '#C5C9C7'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'
